site_name: FlowFile
site_description: A visual ETL tool combining drag-and-drop workflow building with Polars dataframes
site_url: https://edwardvaneechoud.github.io/flowfile/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Building Flows: flows/building.md
  - Nodes:
    - Overview: nodes/index.md
    - Input Nodes: nodes/input.md
    - Transform Nodes: nodes/transform.md
    - Combine Nodes: nodes/combine.md
    - Aggregate Nodes: nodes/aggregate.md
    - Output Nodes: nodes/output.md